# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '2'
# Define services
services:
  # Logstash Service
  logstash:
    #image: bitnami/logstash:latest
    build:
      context: logstash/
    container_name: esp52_logstash
    volumes:
    # - ./logstash:/bitnami/logstash/config
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "52005:52005/tcp"
    expose:
      - "52005"
    networks:
      - esp52
networks:
  esp52:
    driver: bridge
