# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '2'
# Define services
services:
  # Logstash Service
  logstash:
    build:
      context: logstash/
    container_name: esp52_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "52520:52520/tcp"
    expose:
      - "52520"
  # Alarms service
  alarmsservice:
    # Configuration for building the docker image for the alarms service
    image: 192.168.160.48:5000/es-project/alarmsservice9:latest
    container_name: esp52_alarmsservice9
    ports: 
      - "52040:52040"
    expose:
      - "52040"
  # External API service
  externalapi:
    # Configuration for building the docker image for the External API service
    image: 192.168.160.48:5000/es-project/externalapi9:latest
    container_name: esp52_externalapi9
    ports: 
      - "52041:52041"
    expose:
      - "52041" 
  managementservice:
    # Configuration for building the docker image for the Management service
    image: 192.168.160.48:5000/es-project/managementservice9:latest
    container_name: esp52_managementservice9
    ports: 
      - "52042:52042"
    expose:
      - "52042" 
  # Parking Lots service
  parkinglotservice:
    # Configuration for building the docker image for the Parking Lots service
    image: 192.168.160.48:5000/es-project/parkinglotsservice9:latest
    container_name: esp52_parkinglotsservice9
    ports: 
      - "52043:52043"
    expose:
      - "52043" 
    depends_on: 
      - logstash
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.160.18:3306/lametro?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
  # Static info
  staticinfo:
    # Configuration for building the docker image for the Static info service
    image: 192.168.160.48:5000/es-project/staticinfo9:latest
    container_name: esp52_staticinfo9
    ports: 
      - "52044:52044"
    expose:
      - "52044" 
  # Vehicles Service
  vehicleservice:
    # Configuration for building the docker image for the vehicles service
    image: 192.168.160.48:5000/es-project/vehiclesservice8:latest
    container_name: esp52_vehiclesservice8
    ports: 
      - "52038:52038"
    expose:
      - "52038" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.160.18:3306/lametro?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
  # Frontend Service
  frontend:
    image: 192.168.160.48:5000/es-project/projectfrontend9:latest
    container_name: esp52_projectfrontend9
    ports:
      - "52045:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
