server:
  port: 52040
spring:
  kafka:
    consumer:
      #bootstrap-servers: 172.0.0.16:9092
      bootstrap-servers: 192.168.160.18:9092
      group-id: "lametro"
      auto-offset-reset: earliest      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer