#logging:
#  level:
#    root: WARN
#    org.springframework: INFO
#    org.apache.kafka: DEBUG
server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: 172.0.0.16:9092
      group-id: "test-consumer-group"
      auto-offset-reset: earliest      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.0.0.16:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer