server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lametro?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: palavrapasse
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers: 172.0.0.16:9092
      group-id: "lametro"
      auto-offset-reset: earliest      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.0.0.16:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer